name:                genvalidity-appendful
version:             0.0.0.0
github:              "NorfairKing/appendful"
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright: (c) 2020 Tom Sydney Kerckhove"

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - QuickCheck
    - containers
    - genvalidity
    - genvalidity-containers
    - genvalidity-time
    - appendful

tests:
  appendful-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - QuickCheck
      - containers
      - genvalidity-hspec
      - genvalidity-hspec-aeson
      - genvalidity-appendful
      - genvalidity-uuid
      - hspec
      - appendful
      - mtl
      - pretty-show
      - random
      - time
      - uuid

benchmarks:
  genvalidity-appendful-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - genvalidity-criterion
      - genvalidity-appendful
      - appendful
