name: genvalidity-appendful
version: 0.0.0.0
github: "NorfairKing/appendful"
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright: (c) 2020-2022 Tom Sydney Kerckhove"
description: Generators for ppend-only cooperative agreement
license: MIT

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - QuickCheck
    - containers
    - genvalidity
    - genvalidity-containers
    - genvalidity-time
    - appendful

tests:
  appendful-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - QuickCheck
      - containers
      - genvalidity-sydtest
      - genvalidity-sydtest-aeson
      - genvalidity-appendful
      - genvalidity-uuid
      - sydtest
      - appendful
      - mtl
      - pretty-show
      - random
      - time
      - uuid

benchmarks:
  genvalidity-appendful-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - genvalidity-criterion
      - genvalidity-appendful
      - appendful
