name: appendful-persistent
version: 0.0.0.0
github: "NorfairKing/appendful"
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright: (c) 2020-2022 Tom Sydney Kerckhove"
description: Persistent integration for ppend-only cooperative agreement
license: MIT

dependencies:
  - base >= 4.11 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-redundant-constraints
  dependencies:
  - containers
  - appendful
  - microlens
  - persistent

tests:
  appendful-persistent-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - QuickCheck
      - containers
      - genvalidity
      - genvalidity-sydtest
      - genvalidity-appendful
      - genvalidity-persistent
      - sydtest
      - appendful
      - appendful-persistent
      - monad-logger
      - mtl
      - path
      - path-io
      - persistent
      - persistent-sqlite
      - persistent-template
      - text
      - validity
