name:                appendful
version:             0.0.0.0
github:              "NorfairKing/appendful"
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright: (c) 2020 Tom Sydney Kerckhove"


library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-redundant-constraints
  dependencies:
    - aeson
    - base >= 4.11 && < 5
    - containers
    - deepseq
    - mtl
    - validity
    - validity-containers

